"""Generates csrc/pq_footer_consts.h: the parts of the parquet footer (thrift compact FileMetaData)
that do not depend on the data, for trace.parquet and message_trace.parquet.

The footer's fields are written in id order: 1 version, 2 schema, 3 num_rows, 4 row_groups,
5 key_value_metadata (the pandas metadata and ARROW:schema), 6 created_by, 7 column_orders. Only
3 and 4 depend on the data, so pqfast.cpp writes PREFIX (struct start through field 2) +
num_rows + row_groups + SUFFIX (fields 5-7 and the struct's stop byte). This script slices PREFIX
and SUFFIX out of reference files written by pyarrow 15.0.2 (any trace.parquet /
message_trace.parquet from the baseline or from the libparquet writer path,
FASTSIM_LIBPARQUET_WRITER=1):

    python tools/gen_footer_consts.py REF/trace.parquet REF/message_trace.parquet > csrc/pq_footer_consts.h
"""
import struct
import sys


def varint(b, i):
    r = s = 0
    while True:
        c = b[i]
        i += 1
        r |= (c & 0x7F) << s
        s += 7
        if not c & 0x80:
            return r, i


def skip(b, i, t):
    if t in (1, 2):  # bool in a field header carries the value; as a list element it is a byte
        return i
    if t == 3:
        return i + 1
    if t in (4, 5, 6):
        return varint(b, i)[1]
    if t == 7:
        return i + 8
    if t == 8:
        n, i = varint(b, i)
        return i + n
    if t in (9, 10):
        h = b[i]
        i += 1
        n = h >> 4
        if n == 15:
            n, i = varint(b, i)
        et = h & 0x0F
        for _ in range(n):
            i = i + 1 if et in (1, 2) else skip(b, i, et)
        return i
    if t == 12:
        return struct_fields(b, i)[1]
    raise ValueError(f"type {t}")


def struct_fields(b, i):
    """[(field id, start offset of its header, end offset)], offset after the stop byte."""
    out, fid = [], 0
    while True:
        start = i
        h = b[i]
        i += 1
        if h == 0:
            return out, i
        t = h & 0x0F
        if h >> 4:
            fid += h >> 4
        else:
            z, i = varint(b, i)
            fid = (z >> 1) ^ -(z & 1)
        i = skip(b, i, t)
        out.append((fid, start, i))


def consts(path):
    data = open(path, "rb").read()
    assert data[:4] == b"PAR1" and data[-4:] == b"PAR1"
    n = struct.unpack("<I", data[-8:-4])[0]
    foot = data[-8 - n:-8]
    fields, end = struct_fields(foot, 0)
    assert end == len(foot), "trailing bytes after FileMetaData"
    ids = [f[0] for f in fields]
    assert ids == [1, 2, 3, 4, 5, 6, 7], ids
    prefix = foot[:fields[2][1]]
    suffix = foot[fields[4][1]:]
    # the generated code assumes fields 3 and 4 use the short (delta) header form
    assert foot[fields[2][1]] == 0x16 and foot[fields[3][1]] == 0x19
    assert suffix[0] == 0x19  # field 5 follows field 4 with delta 1
    return prefix, suffix


def arr(name, b):
    body = ",".join(str(x) for x in b)
    return f"constexpr unsigned char {name}[] = {{{body}}};\n"


def main():
    tp, ts = consts(sys.argv[1])
    lp, ls = consts(sys.argv[2])
    sys.stdout.write("// Generated by tools/gen_footer_consts.py -- do not edit.\n#pragma once\n\n"
                     "namespace fastsim {\n\n")
    for name, b in (("kTraceFooterPrefix", tp), ("kTraceFooterSuffix", ts),
                    ("kLedgerFooterPrefix", lp), ("kLedgerFooterSuffix", ls)):
        sys.stdout.write(arr(name, b))
    sys.stdout.write("\n}  // namespace fastsim\n")


if __name__ == "__main__":
    main()
