"""Generate edge-case scenarios that stress code paths the public set barely reaches.

The sealed scenarios are generated by the same adapter but may push parameters further. Each
variant here is a mutation of a public scenario that exercises a path the 65 public scenarios
cover thinly or not at all — exchange computation / pipeline delays (agent re-queueing), STP
policies under those delays, the no-``latency_config`` line-distance fallback, deterministic
latency (dense ties), degenerate agent parameters, float-typed integer fields, tiny prices
(negative limit prices are discarded), large populations, frequent megashocks, extreme seeds.

They have no reference traces; the point is to run them through ``scripts/check_identical.py``
against the baseline image, which demands byte-identical output.

    python scripts/make_edge_scenarios.py --out run_outputs/edge_scenarios
    python scripts/check_identical.py --candidate-image <img> \
        --scenarios-dir run_outputs/edge_scenarios --extra-seeds 1
"""

from __future__ import annotations

import argparse
import copy
import json
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SC = REPO / "regression_suite" / "scenarios"


def load(name: str) -> dict:
    return json.loads((SC / f"{name}.json").read_text())


def agents(sc: dict, kind: str) -> list[dict]:
    return [a for a in sc["agent_configs"] if a["agent_type"] == kind]


def variants() -> dict[str, dict]:
    v: dict[str, dict] = {}

    s = load("mp02_stp_oldest_baseline")
    s["exchange_config"].update(ack_delay_ns=2000, compute_delay_ns=40)
    v["e01_stp_oldest_ack_compute_delay"] = s

    s = load("mp01_stp_newest_baseline")
    s["exchange_config"].update(ack_delay_ns=150, compute_delay_ns=300)
    v["e02_stp_newest_compute_requeue"] = s

    s = load("as01_base_mix")
    s["exchange_config"].update(protocol_enforcement=True, compute_delay_ns=60)  # delays, no STP
    v["e03_proto_compute_no_stp"] = s

    s = load("as01_base_mix")
    del s["latency_config"]
    v["e04_no_latency_config_line_model"] = s

    s = load("as03_mm_liquidity_heavy")
    s["latency_config"] = {"model": "deterministic", "params": {"mean_ns": 1000, "min_ns": 0, "max_ns": 1e12}}
    v["e05_deterministic_latency_ties"] = s

    s = load("as01_base_mix")
    for a in agents(s, "NoiseTrader"):
        a["params"]["price_offset_ticks"] = 0
    for a in agents(s, "MarketMaker"):
        a["params"].update(spread_ticks=1, depth_levels=1)
    for a in agents(s, "MomentumTrader"):
        a["params"].update(lookback=1, threshold_ticks=0)
    for a in agents(s, "ValueTrader"):
        a["params"].update(threshold_ticks=0)
    v["e06_degenerate_params"] = s

    s = load("gb_pop_128_agents")
    s["horizon_ns"] = 5_000_000_000
    for a in s["agent_configs"]:
        a["count"] = a["count"] * 3
    v["e07_large_population"] = s

    s = load("as02_scale_up_noise")
    for a in s["agent_configs"]:
        p = a["params"]
        for k in ("price_offset_ticks", "order_size_mean", "order_size_std", "depth_levels", "size_per_level",
                  "lookback", "threshold_ticks"):
            if k in p:
                p[k] = float(p[k]) + (0.5 if k in ("order_size_mean",) else 0.0)
        if "spread_ticks" in p:
            p["spread_ticks"] = 2.5
        if "rebalance_interval_ns" in p:
            p["rebalance_interval_ns"] = float(p["rebalance_interval_ns"])
        a["count"] = float(a["count"])
    s["horizon_ns"] = float(s["horizon_ns"])
    v["e08_float_typed_fields"] = s

    s = load("ca_fat_tail_jumps")
    s["oracle_config"]["params"].update(jump_intensity=25.0, jump_sigma=4000.0)
    s["oracle_config"]["params"]["scheduled_jump"] = {"time_ns": 2_000_000_000, "magnitude": -3000}
    v["e09_frequent_megashocks_plus_jump"] = s

    s = load("as04_value_heavy")
    s["latency_config"] = {"model": "uniform", "params": {"mean_ns": 500, "min_ns": 800, "max_ns": 800}}
    v["e10_uniform_degenerate"] = s

    s = load("as04_value_heavy")
    s["latency_config"] = {"model": "gaussian_unknown", "params": {"mean_ns": 777.7, "min_ns": 100, "max_ns": 5000}}
    v["e11_unknown_latency_model"] = s

    s = load("as01_base_mix")
    s["oracle_config"]["params"]["initial_price"] = 6
    for a in agents(s, "NoiseTrader"):
        a["params"]["price_offset_ticks"] = 9
    v["e12_tiny_prices_negative_limits"] = s

    s = load("ra01_fundamental_shock_mid")
    s["oracle_config"]["params"]["scheduled_jump"] = {"time_ns": 0, "magnitude": -10_000_000}
    v["e13_jump_at_open_clamped_to_zero"] = s

    s = load("as01_base_mix")
    s["seed"] = 0
    v["e14_seed_zero"] = s
    s = load("as01_base_mix")
    s["seed"] = 2**32 - 1
    v["e15_seed_max"] = s

    s = load("as01_base_mix")
    for a in s["agent_configs"]:
        a["params"] = {}
    s["oracle_config"]["params"] = {}
    v["e16_all_defaults"] = s

    s = load("as03_mm_liquidity_heavy")
    for a in agents(s, "MarketMaker"):
        a["params"]["rebalance_interval_ns"] = 300  # faster than the latency: cancels race their orders
    s["horizon_ns"] = 2_000_000_000
    v["e17_mm_faster_than_latency"] = s

    s = load("as01_base_mix")
    for a in agents(s, "NoiseTrader"):
        a["params"]["arrival_rate_hz"] = 0.0
    for a in agents(s, "ValueTrader"):
        a["params"]["arrival_rate_hz"] = -3.0
    v["e18_zero_negative_rates"] = s

    s = load("eq001_pareto_latency_tail")
    s["latency_config"]["params"].update(alpha=0.7, max_ns=5e9)  # very heavy tail, long delays
    v["e19_pareto_very_heavy"] = s

    s = load("as01_base_mix")
    s["latency_config"]["params"].update(sigma=2.5, max_ns=3e9)
    s["horizon_ns"] = 60_000_000_000
    v["e20_lognormal_wide_long"] = s

    s = load("mp03_mm_heavy_newest")
    s["exchange_config"].update(ack_delay_ns=0, compute_delay_ns=1)
    v["e21_compute_delay_1ns"] = s

    s = load("as01_base_mix")
    s["agent_configs"] = [a for a in s["agent_configs"] if a["agent_type"] in ("ValueTrader", "MomentumTrader")]
    v["e22_no_liquidity_providers"] = s

    s = load("as01_base_mix")
    for a in s["agent_configs"]:
        a["count"] = 0
    s["agent_configs"][0]["count"] = 1
    v["e23_single_agent"] = s

    s = load("as06_throughput_fast")
    s["exchange_config"].update(protocol_enforcement=True, stp_policy="cancel_oldest", ack_delay_ns=0,
                                compute_delay_ns=0)
    v["e24_stp_oldest_no_delay_throughput"] = s
    return v


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "run_outputs" / "edge_scenarios"))
    args = ap.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for name, sc in variants().items():
        sc = copy.deepcopy(sc)
        sc["scenario_id"] = str(uuid.uuid5(uuid.NAMESPACE_URL, f"fastsim-edge/{name}"))
        sc["description"] = f"edge-case variant {name} (local testing only)"
        (out / f"{name}.json").write_text(json.dumps(sc, indent=2))
    print(f"wrote {len(variants())} edge scenarios to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
